---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord-bot
  namespace: app-preview
spec:
  type: discord
  channel: general
  address: hhttps://discord.com/api/webhooks/1342881189115199612/JL3CuBozI4DFelztw35VZ2l4rnT6rSTQiO0Yvi6TSEyKkBrNbQc5amstSZwQhBpvfmCi
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord-alert
  namespace: app-preview
spec:
  providerRef:
    name: discord-bot
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: HelmRelease
      name: '*'